export const docentes = [
    {
        id: 126,
        login: "cecilia",
        password: "123456",
        nombre: "Cecilia",
        apellido: "Vizcaino",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "3453223",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351433112",
        direccion: "6718 Christop Street",
        fechanacimiento: '10/12/1980'
    },
    {
        id: 127,
        login: "rosa",
        password: "123456",
        nombre: "Rosa ",
        apellido: "Olivares",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "34563223",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "35154534",
        direccion: "74731 Braun Village",
        fechanacimiento: '10/12/1984'
    },

    {
        id: 128,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "21342323",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "35145335",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 129,
        login: "valeriano",
        password: "123456",
        nombre: "Valeriano",
        apellido: "Alcantara",
        correo: "alcantaraval@gmail.com",
        idrol: 1,
        legajo: "212435344",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 130,
        login: "william",
        password: "123456",
        nombre: "William",
        apellido: "Cerezo",
        correo: "cerezowill@gmail.com",
        idrol: 1,
        legajo: "3534322",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 131,
        login: "marti",
        password: "123456",
        nombre: "Marti",
        apellido: "Real",
        correo: "martireal@gmail.com",
        idrol: 1,
        legajo: "23242524",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 132,
        login: "leire",
        password: "123456",
        nombre: "Leire",
        apellido: "Vivaz",
        correo: "leirevivaz@gmail.com",
        idrol: 1,
        legajo: "24332424",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 133,
        login: "jessica",
        password: "123456",
        nombre: "Jessica",
        apellido: "Ribes",
        correo: "jessicaribes@gmail.com",
        idrol: 1,
        legajo: "24231423",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 134,
        login: "vic",
        password: "123456",
        nombre: "Victor",
        apellido: "Ginez",
        correo: "victorginez@gmail.com",
        idrol: 1,
        legajo: "34342322",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 135,
        login: "enric",
        password: "123456",
        nombre: "Enric ",
        apellido: "Miguez",
        correo: "miguezenric@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 136,
        login: "dina",
        password: "123456",
        nombre: "Dina",
        apellido: "Ruiz",
        correo: "ruizdina@gmail.com",
        idrol: 1,
        legajo: "324531211",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 137,
        login: "lazaro",
        password: "123456",
        nombre: "Lazaro",
        apellido: "Martinez",
        correo: "lazaromartinez@gmail.com",
        idrol: 1,
        legajo: "22321442",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 138,
        login: "luci",
        password: "123456",
        nombre: "Lucia",
        apellido: "Cabanillas",
        correo: "cabanillaslucia@gmail.com",
        idrol: 1,
        legajo: "23421242",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 139,
        login: "joan",
        password: "123456",
        nombre: "Joan",
        apellido: "Puertas",
        correo: "puertasjoan@gmail.com",
        idrol: 1,
        legajo: "2345225",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 140,
        login: "dawn",
        password: "123456",
        nombre: "Dawn",
        apellido: "Ellis",
        correo: "ellisdawn@gmail.com",
        idrol: 1,
        legajo: "23421232",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "35134222",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 141,
        login: "rachael",
        password: "123456",
        nombre: "Rachael",
        apellido: "Woodward",
        correo: "woodwardrachael@gmail.com",
        idrol: 1,
        legajo: "23453223",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "35133242",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 142,
        login: "steven",
        password: "123456",
        nombre: "Steven",
        apellido: "Pruitt",
        correo: "pruittsteven@gmail.com",
        idrol: 1,
        legajo: "23521452",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351345342",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 143,
        login: "kaitlyn",
        password: "123456",
        nombre: "Kaitlyn",
        apellido: "Frost",
        correo: "frostkaytlyn@gmail.com",
        idrol: 1,
        legajo: "224533533",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351232453",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 144,
        login: "dennis",
        password: "123456",
        nombre: "Dennis",
        apellido: "Powell",
        correo: "powelldennis@gmail.com",
        idrol: 1,
        legajo: "245431132",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "3513533",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 145,
        login: "michael",
        password: "123456",
        nombre: "Michael",
        apellido: "Vaughan",
        correo: "vaughan@gmail.com",
        idrol: 1,
        legajo: "23445636",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351354323",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 146,
        login: "jonathan",
        password: "123456",
        nombre: "Jonathan",
        apellido: "Mann",
        correo: "mann@gmail.com",
        idrol: 1,
        legajo: "34225522",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "35134522",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 147,
        login: "Lauren",
        password: "123456",
        nombre: "Lauren",
        apellido: "Richards",
        correo: "richardlauren@gmail.com",
        idrol: 1,
        legajo: "23456231",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "35134522",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 148,
        login: "ronald",
        password: "123456",
        nombre: "Ronald",
        apellido: "Scott",
        correo: "scottronald@gmail.com",
        idrol: 1,
        legajo: "235214522",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351453362",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 149,
        login: "kristie",
        password: "123456",
        nombre: "Kristie",
        apellido: "Fox",
        correo: "foxkristie@gmail.com",
        idrol: 1,
        legajo: "255742342",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351337578",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },


]