export const docentes = [
    {
        id: 126,
        login: "cecilia",
        password: "123456",
        nombre: "Cecilia",
        apellido: "Vizcaino",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "3453223",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351433112",
        direccion: "6718 Christop Street",
        fechanacimiento: '10/12/1980'
    },
    {
        id: 127,
        login: "rosa",
        password: "123456",
        nombre: "Rosa ",
        apellido: "Olivares",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "34563223",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "35154534",
        direccion: "74731 Braun Village",
        fechanacimiento: '10/12/1984'
    },

    {
        id: 128,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 129,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 130,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 131,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 132,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 133,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 134,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 135,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 136,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 137,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 138,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 139,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 140,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 141,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 142,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 143,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 144,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 145,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 146,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 147,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 148,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },

    {
        id: 149,
        login: "roberto",
        password: "123456",
        nombre: "Roberto",
        apellido: "Lopez",
        correo: "docente@gmail.com",
        idrol: 1,
        legajo: "312313123",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351",
        direccion: "",
        fechanacimiento: '10/12/1980'
    },


]