export const tutores = [

    {
        id: 63,
        login: "fernando",
        password: "123456",
        nombre: "Fernando",
        apellido: "Carnero",
        correo: "carnerofernando@gmail.com",
        idRol: 6,
        legajo: "2308654",
        sexo: "M",
        localidad: "Buenos Aires",
        telefono: "55452445",
        direccion: "Caseros 563",

    },
    {
        id: 64,
        login: "celestino",
        password: "123456",
        nombre: "Celestino ",
        apellido: "Aguilar",
        correo: "aguilarcelestino@gmail.com",
        idRol: 6,
        legajo: "304352",
        sexo: "M",
        localidad: "Buenos Aires",
        telefono: "35165642",
        direccion: "Caseros 234",

    },
    {
        id: 65,
        login: "stefan",
        password: "123456",
        nombre: "Stefan",
        apellido: "Paredez",
        correo: "paredezstefan @gmail.com",
        idRol: 6,
        legajo: "200333",
        sexo: "M",
        localidad: "Buenos Aires",
        telefono: "351656552",
        direccion: "Casas 434",

    },
    {
        id: 66,
        login: "justo",
        password: "123456",
        nombre: "Justo",
        apellido: "Rodriguez",
        correo: "rodriguez@gmail.com",
        idRol: 6,
        legajo: "3353233",
        sexo: "M",
        localidad: "Buenos Aires",
        telefono: "351467532",
        direccion: "Siempre Viva 343",

    },
    {
        id: 67,
        login: "jacinto",
        password: "123456",
        nombre: "Jacinto",
        apellido: "Del Valle",
        correo: "delvallejacinto@gmail.com",
        idRol: 6,
        legajo: "3423431",
        sexo: "M",
        localidad: "Buenos Aires",
        telefono: "35143752",
        direccion: "Caseros 343",

    },
    {
        id: 68,
        login: "adrian",
        password: "123456",
        nombre: "Adrian",
        apellido: "Cardoso",
        correo: "cardosoadrian@gmail.com",
        idRol: 6,
        legajo: "237561",
        sexo: "M",
        localidad: "Buenos Aires",
        telefono: "35156564",
        direccion: "Caseros 343",

    },
    {
        id: 69,
        login: "elisa",
        password: "123456",
        nombre: "Elisa ",
        apellido: "Urbano",
        correo: "urbanoelisa@gmail.com",
        idRol: 6,
        legajo: "2345412",
        sexo: "F",
        localidad: "Buenos Aires",
        telefono: "35145552",
        direccion: "Caseros 323"
    },
    {
        id: 70,
        login: "sacramento",
        password: "123456",
        nombre: "Sacramento",
        apellido: "Trigo",
        correo: "trigosacramento@gmail.com",
        idRol: 6,
        legajo: "235212",
        sexo: "M",
        localidad: "Buenos Aires",
        telefono: "351645452",
        direccion: "Caseros 423"
    },
    {
        id: 71,
        login: "eusebio",
        password: "123456",
        nombre: "Eusebio",
        apellido: "Lucena",
        correo: "lucenaeusebio@gmail.com",
        idRol: 6,
        legajo: "2031242",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "35145352",
        direccion: "9922 Domenica Passage"
    },
    {
        id: 72,
        login: "moussa",
        password: "123456",
        nombre: "Moussa ",
        apellido: "Gomis",
        correo: "gomismoussa@gmail.com",
        idRol: 6,
        legajo: "2003312",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "35163432",
        direccion: "6844 Abshire Plaza"
    },
    {
        id: 73,
        login: "pedro",
        password: "123456",
        nombre: "Pedro",
        apellido: "Morillas",
        correo: "morillaspedro@gmail.com",
        idRol: 6,
        legajo: "204122",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351645352",
        direccion: "1352 Alberta Loaf"
    },
    {
        id: 74,
        login: "virgilio",
        password: "123456",
        nombre: "Virgilio ",
        apellido: "Puerta",
        correo: "puertavirgilio@gmail.com",
        idRol: 6,
        legajo: "204312",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "3513452",
        direccion: "12900 White Spur"
    },
    {
        id: 75,
        login: "fabian",
        password: "123456",
        nombre: "Fabian",
        apellido: "Penalver",
        correo: "penalverfabian@gmail.com",
        idRol: 6,
        legajo: "204332",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "3516124352",
        direccion: "20424 Maximillian Hollow"
    },
    {
        id: 76,
        login: "noelia",
        password: "123456",
        nombre: "Noelia",
        apellido: "Crespo",
        correo: "cresponoelia@gmail.com",
        idRol: 6,
        legajo: "2031253",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "35134542",
        direccion: "035 Roberto Forges"
    },
    {
        id: 77,
        login: "fermina",
        password: "123456",
        nombre: "Fermina",
        apellido: "Galindo",
        correo: "galindofermina@gmail.com",
        idRol: 6,
        legajo: "2034212",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351452452",
        direccion: "124 Pollich Corner"
    },
    {
        id: 78,
        login: "rocio",
        password: "123456",
        nombre: "Rocio",
        apellido: "del Moral",
        correo: "delmoralrocio@gmail.com",
        idRol: 6,
        legajo: "2003433",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351565442",
        direccion: "966 Evalyn Manor"
    },
    {
        id: 79,
        login: "ibrahim",
        password: "123456",
        nombre: "Ibrahim",
        apellido: "Bustamante",
        correo: "bustamanteibrahim@gmail.com",
        idRol: 6,
        legajo: "200344",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "3515652452",
        direccion: "68313 Dawson Meadow"
    },
    {
        id: 80,
        login: "alicia",
        password: "123456",
        nombre: "Alicia",
        apellido: "Cano",
        correo: "canoalicia@gmail.com",
        idRol: 6,
        legajo: "20044232",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "35156432",
        direccion: "4002 Schiller Creek"
    },
    {
        id: 81,
        login: "marcos",
        password: "123456",
        nombre: "Marcos",
        apellido: "Garzon",
        correo: "garzonmarcos@gmail.com",
        idRol: 6,
        legajo: "2023654",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351634252",
        direccion: "4042 Schiller Creek"
    },
    {
        id: 82,
        login: "yassin",
        password: "123456",
        nombre: "Yassin",
        apellido: "Acuña",
        correo: "acuñayassin@gmail.com",
        idRol: 6,
        legajo: "20643432",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "3514544223",
        direccion: "4508 Madelyn Ways"
    },
    {
        id: 83,
        login: "antonio ",
        password: "123456",
        nombre: "Antonio",
        apellido: "Puente",
        correo: "puenteantonio@gmail.com",
        idRol: 6,
        legajo: "2034324",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351634452",
        direccion: "9414 Koepp Loop"
    },
    {
        id: 84,
        login: "gertrudis",
        password: "123456",
        nombre: "Gertrudis",
        apellido: "Aranda",
        correo: "arandagertrudis@gmail.com",
        idRol: 6,
        legajo: "30564343",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351545652",
        direccion: "80586 Petra Haven"
    },
    {
        id: 85,
        login: "george",
        password: "123456",
        nombre: "George",
        apellido: "Gamero",
        correo: "gamerogeorge@gmail.com",
        idRol: 6,
        legajo: "2043432",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "35163552",
        direccion: "19289 Spencer Valleys"
    },
    {
        id: 86,
        login: "francisco",
        password: "123456",
        nombre: "Francisco ",
        apellido: "Hernando",
        correo: "hernandofrancisco@gmail.com",
        idRol: 6,
        legajo: "7564434",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351612452",
        direccion: "19765 Spencer Valleys"
    },
    {
        id: 87,
        login: "adil",
        password: "123456",
        nombre: "Adil",
        apellido: "Martos",
        correo: "martosadil@gmail.com",
        idRol: 6,
        legajo: "2008546",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "3514652",
        direccion: "0032 Krajcik Path"
    },
    {
        id: 89,
        login: "pedro",
        password: "123456",
        nombre: "Pedro",
        apellido: "Moya",
        correo: "moyapedro@gmail.com",
        idRol: 6,
        legajo: "2006568",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351345452",
        direccion: "3655 Jairo Mall"
    },
    {
        id: 90,
        login: "lina",
        password: "123456",
        nombre: "Lina",
        apellido: "Diego",
        correo: "diegolina@gmail.com",
        idRol: 6,
        legajo: "206667",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "3514552",
        direccion: "0728 Raymundo Plains"
    },
    {
        id: 91,
        login: "ricardo",
        password: "123456",
        nombre: "Ricardo",
        apellido: "Cerda",
        correo: "cerdaricardo@gmail.com",
        idRol: 6,
        legajo: "543888",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351612452",
        direccion: "1760 Renner Loop"
    },
    {
        id: 92,
        login: "gabriel",
        password: "123456",
        nombre: "Gabriel",
        apellido: "Nogales",
        correo: "nogalesgabriel@gmail.com",
        idRol: 6,
        legajo: "3346695",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351656452",
        direccion: "6199 Mara Street"
    },
    {
        id: 93,
        login: "nestor",
        password: "123456",
        nombre: "Nestor",
        apellido: "Rueda",
        correo: "ruedanestor@gmail.com",
        idRol: 6,
        legajo: "2055876",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "35145652",
        direccion: "4874 Bauch Junctions"
    },
    {
        id: 94,
        login: "ahmed",
        password: "123456",
        nombre: "Ahmed",
        apellido: "Santana",
        correo: "santanaahmed@gmail.com",
        idRol: 6,
        legajo: "204532",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "3516345452",
        direccion: "98849 Reilly Ports"
    },
    {
        id: 95,
        login: "vicente",
        password: "123456",
        nombre: "Vicente",
        apellido: "Quiros",
        correo: "quirosvicente@gmail.com",
        idRol: 6,
        legajo: "2034532",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "35145452",
        direccion: "2750 Trantow Stream"
    },
    {
        id: 96,
        login: "nancy",
        password: "123456",
        nombre: "Nancy",
        apellido: "Mata",
        correo: "matanancy@gmail.com",
        idRol: 6,
        legajo: "2034322",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "35134452",
        direccion: "4283 Schamberger Crossroad"
    },
    {
        id: 97,
        login: "eloi",
        password: "123456",
        nombre: "Eloi",
        apellido: "Canovas",
        correo: "canovaseloi@gmail.com",
        idRol: 6,
        legajo: "307543",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "3516334452",
        direccion: "5544 Weissnat Rest"
    },
    {
        id: 98,
        login: "ramon",
        password: "123456",
        nombre: "Ramon",
        apellido: "Peinado",
        correo: "peinadoramon@gmail.com",
        idRol: 6,
        legajo: "20522323",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351612452",
        direccion: "369 Nathen Well"
    },
    {
        id: 99,
        login: "adela",
        password: "123456",
        nombre: "Adela",
        apellido: "Cid",
        correo: "cidadela@gmail.com",
        idRol: 6,
        legajo: "2043453",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "3514552",
        direccion: "251 Reinger Road"
    },
    {
        id: 100,
        login: "concepcio",
        password: "123456",
        nombre: "Concepcio ",
        apellido: "Bermudez",
        correo: "bermudezconcepcio@gmail.com",
        idRol: 6,
        legajo: "201323",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "35145452",
        direccion: "3781 Gene Mission"
    },
    {
        id: 101,
        login: "moussa",
        password: "123456",
        nombre: "Moussa  ",
        apellido: "Lopez",
        correo: "lopezmoussa@gmail.com",
        idRol: 6,
        legajo: "206432",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351345452",
        direccion: "2553 Creola Springs"
    },
    {
        id: 102,
        login: "fabiola ",
        password: "123456",
        nombre: "Fabiola ",
        apellido: "Miralles",
        correo: "mirallesfabiola@gmail.com",
        idRol: 6,
        legajo: "2043532",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351612452",
        direccion: "1432 Hudson Point"
    },
    {
        id: 103,
        login: "melanie",
        password: "123456",
        nombre: "Melanie",
        apellido: "Espin",
        correo: "espinmelanie@gmail.com",
        idRol: 6,
        legajo: "2045324",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "35145452",
        direccion: "533 Gleason Wall"
    },
    {
        id: 104,
        login: "carlota ",
        password: "123456",
        nombre: "Carlota ",
        apellido: "Padilla",
        correo: "padillacarlota@gmail.com",
        idRol: 6,
        legajo: "2046332",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "3516345452",
        direccion: "3718 Haag Forks"
    },
    {
        id: 105,
        login: "pepe",
        password: "123456",
        nombre: "Pepe",
        apellido: "Varela",
        correo: "varelapepe@gmail.com",
        idRol: 6,
        legajo: "2345543",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351345452",
        direccion: "1081 Jones Forge"
    },
    {
        id: 106,
        login: "gines",
        password: "123456",
        nombre: "Gines  ",
        apellido: "Boix",
        correo: "boixgines@gmail.com",
        idRol: 6,
        legajo: "2024332",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "3513452",
        direccion: "073 Franecki Junction"
    },
    {
        id: 107,
        login: "leandro",
        password: "123456",
        nombre: "Leandro",
        apellido: "Alcalde",
        correo: "alcaldeleandro@gmail.com",
        idRol: 6,
        legajo: "2064334",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351342452",
        direccion: "79919 Amparo Route"
    },
    {
        id: 108,
        login: "henar",
        password: "123456",
        nombre: "Henar ",
        apellido: "Camino",
        correo: "caminohenar@gmail.com",
        idRol: 6,
        legajo: "2043322",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351334452",
        direccion: "13776 Angela Gardens"
    },
    {
        id: 109,
        login: "ibai",
        password: "123456",
        nombre: "Ibai",
        apellido: "Chaparro",
        correo: "chaparroibai@gmail.com",
        idRol: 6,
        legajo: "2064644",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "35134452",
        direccion: "90585 Isabel Union"
    },
    {
        id: 110,
        login: "alexia",
        password: "123456",
        nombre: "Alexia ",
        apellido: "Luna",
        correo: "lunaalexia@gmail.com",
        idRol: 6,
        legajo: "2056343",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "35163452",
        direccion: "1483 Stoltenberg Viaduct"
    },
    {
        id: 111,
        login: "irene ",
        password: "123456",
        nombre: "Irene",
        apellido: "Fraga",
        correo: "fragairene@gmail.com",
        idRol: 6,
        legajo: "2353453",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "35134352",
        direccion: "91963 Kenyatta Underpass"
    },
    {
        id: 112,
        login: "juana ",
        password: "123456",
        nombre: "Juana",
        apellido: "Ferrer",
        correo: "ferrerjuana@gmail.com",
        idRol: 6,
        legajo: "2142434",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351634452",
        direccion: "59862 Bernhard Valleys"
    },
    {
        id: 113,
        login: "giovanni",
        password: "123456",
        nombre: "Giovanni",
        apellido: "Giraldo",
        correo: "giraldogiovanni@gmail.com",
        idRol: 6,
        legajo: "2134342",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "35134352",
        direccion: "5704 Kuhn Avenue"
    },
    {
        id: 114,
        login: "jeronima",
        password: "123456",
        nombre: "Jeronima",
        apellido: "Lozano",
        correo: "lozanojeronima@gmail.com",
        idRol: 6,
        legajo: "205342",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351322452",
        direccion: "6845 Wolf Village"
    },
    {
        id: 115,
        login: "nicolasa ",
        password: "123456",
        nombre: "Nicolasa ",
        apellido: "Cristobal",
        correo: "cristobalnicolasa@gmail.com",
        idRol: 6,
        legajo: "2056443",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "35163433452",
        direccion: "137 VonRueden Pine"
    },
    {
        id: 116,
        login: "flora ",
        password: "123456",
        nombre: "Flora ",
        apellido: "Sierra",
        correo: "sierraflora@gmail.com",
        idRol: 6,
        legajo: "2143334",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "35164542",
        direccion: "52991 Camren Wells"
    },
    {
        id: 117,
        login: "alberto",
        password: "123456",
        nombre: "Alberto ",
        apellido: "Palazon",
        correo: "palazonalberto@gmail.com",
        idRol: 6,
        legajo: "2365564",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "35134352",
        direccion: "42369 Cassin Tunnel"
    },
    {
        id: 118,
        login: "julian ",
        password: "123456",
        nombre: "Julian ",
        apellido: "Jurado",
        correo: "juradojulian@gmail.com",
        idRol: 6,
        legajo: "205334",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351634452",
        direccion: "219 Becker Stravenue"
    },
    {
        id: 119,
        login: "gabriela",
        password: "123456",
        nombre: "Gabriela ",
        apellido: "Navarrete",
        correo: "navarretegabriela@gmail.com",
        idRol: 6,
        legajo: "215533",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351343452",
        direccion: "058 Rolfson Cove"
    },
    {
        id: 120,
        login: "rut",
        password: "123456",
        nombre: "Rut",
        apellido: "San Jose",
        correo: "sanjoserurutben@gmail.com",
        idRol: 6,
        legajo: "2085534",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "35134452",
        direccion: "71289 Steuber Hill"
    },
    {
        id: 121,
        login: "amparo",
        password: "123456",
        nombre: "Amparo",
        apellido: "Mendoza",
        correo: "mendozaamparo@gmail.com",
        idRol: 6,
        legajo: "2043343",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "35134332",
        direccion: "376 Wyman Cliff"
    },
    {
        id: 122,
        login: "nayra",
        password: "123456",
        nombre: "Nayra ",
        apellido: "Losada",
        correo: "losadanayra@gmail.com",
        idRol: 6,
        legajo: "2345344",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "35162352",
        direccion: "04517 Aufderhar Circle"
    },
    {
        id: 123,
        login: "iker",
        password: "123456",
        nombre: "Iker ",
        apellido: "Font",
        correo: "fontiker@gmail.com",
        idRol: 6,
        legajo: "2433532",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "33433452",
        direccion: "72891 Bednar Tunnel"
    },
]

