export const tutores = [

    {
        id: 62,
        login: "fernando",
        password: "123456",
        nombre: "Fernando",
        apellido: "Carnero",
        correo: "tutor@gmail.com",
        idRol: 6,
        legajo: "23086554",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351524425",
        direccion: "687 Feil Street",
        fechanacimiento: "30/05/1975"

    },
    {
        id: 63,
        login: "celestino",
        password: "123456",
        nombre: "Celestino ",
        apellido: "Aguilar",
        correo: "aguilarcelestino@gmail.com",
        idRol: 6,
        legajo: "30435322",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351651642",
        direccion: "228 Kiehn Passage",
        fechanacimiento: "25/01/1974"
    },
    {
        id: 64,
        login: "stefan",
        password: "123456",
        nombre: "Stefan",
        apellido: "Paredez",
        correo: "paredezstefan @gmail.com",
        idRol: 6,
        legajo: "24322333",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351656552",
        direccion: "97440 Swift Islands",
        fechanacimiento: "25/01/1974"
    },
    {
        id: 65,
        login: "justo",
        password: "123456",
        nombre: "Justo",
        apellido: "Rodriguez",
        correo: "rodriguezjusto@gmail.com",
        idRol: 6,
        legajo: "33513233",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351467532",
        direccion: "9123 Paucek Plaza",
        fechanacimiento: "02/05/1979"
    },
    {
        id: 66,
        login: "jacinto",
        password: "123456",
        nombre: "Jacinto",
        apellido: "Del Valle",
        correo: "delvallejacinto@gmail.com",
        idRol: 6,
        legajo: "34234431",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351437152",
        direccion: "83014 Vaughn Cove",
        fechanacimiento: "23/01/1974"
    },
    {
        id: 67,
        login: "adrian",
        password: "123456",
        nombre: "Adrian",
        apellido: "Cardoso",
        correo: "cardosoadrian@gmail.com",
        idRol: 6,
        legajo: "237561",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351576564",
        direccion: "75027 Vaughn Cove",
        fechanacimiento: "14/05/1975"
    },
    {
        id: 68,
        login: "elisa",
        password: "123456",
        nombre: "Elisa ",
        apellido: "Urbano",
        correo: "urbanoelisa@gmail.com",
        idRol: 6,
        legajo: "23454212",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351455852",
        direccion: "73796 Guido Divide",
        fechanacimiento: "17/05/1971"
    },
    {
        id: 69,
        login: "sacramento",
        password: "123456",
        nombre: "Sacramento",
        apellido: "Trigo",
        correo: "trigosacramento@gmail.com",
        idRol: 6,
        legajo: "23553212",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351645452",
        direccion: "2992 Danny Creek",
        fechanacimiento: "24/03/1973"
    },
    {
        id: 70,
        login: "eusebio",
        password: "123456",
        nombre: "Eusebio",
        apellido: "Lucena",
        correo: "lucenaeusebio@gmail.com",
        idRol: 6,
        legajo: "20231242",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351453152",
        direccion: "9922 Domenica Passage",
        fechanacimiento: "03/10/1977"
    },
    {
        id: 71,
        login: "moussa",
        password: "123456",
        nombre: "Moussa ",
        apellido: "Gomis",
        correo: "gomismoussa@gmail.com",
        idRol: 6,
        legajo: "22442312",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351634329",
        direccion: "6844 Abshire Plaza",
        fechanacimiento: "09/12/1979"
    },
    {
        id: 72,
        login: "pedro",
        password: "123456",
        nombre: "Pedro",
        apellido: "Morillas",
        correo: "morillaspedro@gmail.com",
        idRol: 6,
        legajo: "20456122",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351645352",
        direccion: "1352 Alberta Loaf",
        fechanacimiento: "24/01/1980"
    },
    {
        id: 73,
        login: "virgilio",
        password: "123456",
        nombre: "Virgilio ",
        apellido: "Puerta",
        correo: "puertavirgilio@gmail.com",
        idRol: 6,
        legajo: "20432112",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351345212",
        direccion: "12900 White Spur",
        fechanacimiento: "24/01/1980"
    },
    {
        id: 74,
        login: "fabian",
        password: "123456",
        nombre: "Fabian",
        apellido: "Penalver",
        correo: "penalverfabian@gmail.com",
        idRol: 6,
        legajo: "20433232",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351612432",
        direccion: "20424 Maximillian Hollow",
        fechanacimiento: "15/09/1979"
    },
    {
        id: 75,
        login: "noelia",
        password: "123456",
        nombre: "Noelia",
        apellido: "Crespo",
        correo: "cresponoelia@gmail.com",
        idRol: 6,
        legajo: "20312253",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351345421",
        direccion: "035 Roberto Forges",
        fechanacimiento: "08/02/1982"
    },
    {
        id: 76,
        login: "fermina",
        password: "123456",
        nombre: "Fermina",
        apellido: "Galindo",
        correo: "galindofermina@gmail.com",
        idRol: 6,
        legajo: "20342212",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351452452",
        direccion: "124 Pollich Corner",
        fechanacimiento: "07/05/1981"
    },
    {
        id: 77,
        login: "rocio",
        password: "123456",
        nombre: "Rocio",
        apellido: "del Moral",
        correo: "delmoralrocio@gmail.com",
        idRol: 6,
        legajo: "20033433",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351565442",
        direccion: "966 Evalyn Manor",
        fechanacimiento: "24/02/1978"
    },
    {
        id: 78,
        login: "ibrahim",
        password: "123456",
        nombre: "Ibrahim",
        apellido: "Bustamante",
        correo: "bustamanteibrahim@gmail.com",
        idRol: 6,
        legajo: "20210344",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351652452",
        direccion: "68313 Dawson Meadow",
        fechanacimiento: "24/02/1978"
    },
    {
        id: 79,
        login: "alicia",
        password: "123456",
        nombre: "Alicia",
        apellido: "Cano",
        correo: "canoalicia@gmail.com",
        idRol: 6,
        legajo: "20044232",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351564329",
        direccion: "4002 Schiller Creek",
        fechanacimiento: "29/04/1978"
    },
    {
        id: 80,
        login: "marcos",
        password: "123456",
        nombre: "Marcos",
        apellido: "Garzon",
        correo: "garzonmarcos@gmail.com",
        idRol: 6,
        legajo: "20231654",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351634252",
        direccion: "4042 Schiller Creek",
        fechanacimiento: "29/04/1978"
    },
    {
        id: 81,
        login: "yassin",
        password: "123456",
        nombre: "Yassin",
        apellido: "Acuña",
        correo: "acuñayassin@gmail.com",
        idRol: 6,
        legajo: "20643432",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351454422",
        direccion: "4508 Madelyn Ways",
        fechanacimiento: "01/07/1972"
    },
    {
        id: 82,
        login: "antonio ",
        password: "123456",
        nombre: "Antonio",
        apellido: "Puente",
        correo: "puenteantonio@gmail.com",
        idRol: 6,
        legajo: "20342324",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351634452",
        direccion: "9414 Koepp Loop",
        fechanacimiento: "13/03/1980"
    },
    {
        id: 83,
        login: "gertrudis",
        password: "123456",
        nombre: "Gertrudis",
        apellido: "Aranda",
        correo: "arandagertrudis@gmail.com",
        idRol: 6,
        legajo: "30564343",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351545652",
        direccion: "80586 Petra Haven",
        fechanacimiento: "13/03/1975"
    },
    {
        id: 84,
        login: "george",
        password: "123456",
        nombre: "George",
        apellido: "Gamero",
        correo: "gamerogeorge@gmail.com",
        idRol: 6,
        legajo: "20434328",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351635528",
        direccion: "19289 Spencer Valleys",
        fechanacimiento: "19/12/1978"
    },
    {
        id: 85,
        login: "francisco",
        password: "123456",
        nombre: "Francisco ",
        apellido: "Hernando",
        correo: "hernandofrancisco@gmail.com",
        idRol: 6,
        legajo: "23164434",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351612452",
        direccion: "19765 Spencer Valleys",
        fechanacimiento: "19/12/1979"
    },
    {
        id: 86,
        login: "adil",
        password: "123456",
        nombre: "Adil",
        apellido: "Martos",
        correo: "martosadil@gmail.com",
        idRol: 6,
        legajo: "20085463",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351465276",
        direccion: "0032 Krajcik Path",
        fechanacimiento: "19/12/1978"
    },
    {
        id: 87,
        login: "pedro",
        password: "123456",
        nombre: "Pedro",
        apellido: "Moya",
        correo: "moyapedro@gmail.com",
        idRol: 6,
        legajo: "20026568",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351345452",
        direccion: "3655 Jairo Mall",
        fechanacimiento: "17/04/1982"
    },
    {
        id: 88,
        login: "lina",
        password: "123456",
        nombre: "Lina",
        apellido: "Diego",
        correo: "diegolina@gmail.com",
        idRol: 6,
        legajo: "20645667",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351455267",
        direccion: "0728 Raymundo Plains",
        fechanacimiento: "17/04/1982"
    },
    {
        id: 89,
        login: "ricardo",
        password: "123456",
        nombre: "Ricardo",
        apellido: "Cerda",
        correo: "cerdaricardo@gmail.com",
        idRol: 6,
        legajo: "23413888",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351612452",
        direccion: "1760 Renner Loop",
        fechanacimiento: "24/12/1973"
    },
    {
        id: 90,
        login: "gabriel",
        password: "123456",
        nombre: "Gabriel",
        apellido: "Nogales",
        correo: "nogalesgabriel@gmail.com",
        idRol: 6,
        legajo: "23346695",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351656452",
        direccion: "6199 Mara Street",
        fechanacimiento: "08/06/1981"
    },
    {
        id: 91,
        login: "nestor",
        password: "123456",
        nombre: "Nestor",
        apellido: "Rueda",
        correo: "ruedanestor@gmail.com",
        idRol: 6,
        legajo: "20455876",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351456524",
        direccion: "4874 Bauch Junctions",
        fechanacimiento: "15/11/1969"
    },
    {
        id: 92,
        login: "ahmed",
        password: "123456",
        nombre: "Ahmed",
        apellido: "Santana",
        correo: "santanaahmed@gmail.com",
        idRol: 6,
        legajo: "20498532",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351634542",
        direccion: "98849 Reilly Ports",
        fechanacimiento: "01/07/1981"
    },
    {
        id: 93,
        login: "vicente",
        password: "123456",
        nombre: "Vicente",
        apellido: "Quiros",
        correo: "quirosvicente@gmail.com",
        idRol: 6,
        legajo: "20394532",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351454528",
        direccion: "2750 Trantow Stream",
        fechanacimiento: "30/05/1969"
    },
    {
        id: 94,
        login: "nancy",
        password: "123456",
        nombre: "Nancy",
        apellido: "Mata",
        correo: "matanancy@gmail.com",
        idRol: 6,
        legajo: "203594322",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "35134452",
        direccion: "4283 Schamberger Crossroad",
        fechanacimiento: "20/05/1969"
    },
    {
        id: 95,
        login: "eloi",
        password: "123456",
        nombre: "Eloi",
        apellido: "Canovas",
        correo: "canovaseloi@gmail.com",
        idRol: 6,
        legajo: "30787543",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351633452",
        direccion: "5544 Weissnat Rest",
        fechanacimiento: "03/05/1969"
    },
    {
        id: 96,
        login: "ramon",
        password: "123456",
        nombre: "Ramon",
        apellido: "Peinado",
        correo: "peinadoramon@gmail.com",
        idRol: 6,
        legajo: "20522323",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351612452",
        direccion: "369 Nathen Well",
        fechanacimiento: "08/05/1969"
    },
    {
        id: 97,
        login: "adela",
        password: "123456",
        nombre: "Adela",
        apellido: "Cid",
        correo: "cidadela@gmail.com",
        idRol: 6,
        legajo: "20436453",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351455212",
        direccion: "251 Reinger Road",
        fechanacimiento: "08/05/1987"
    },
    {
        id: 98,
        login: "concepcio",
        password: "123456",
        nombre: "Concepcio ",
        apellido: "Bermudez",
        correo: "bermudezconcepcio@gmail.com",
        idRol: 6,
        legajo: "20132983",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351456452",
        direccion: "3781 Gene Mission",
        fechanacimiento: "17/12/1972"
    },
    {
        id: 99,
        login: "moussa",
        password: "123456",
        nombre: "Moussa  ",
        apellido: "Lopez",
        correo: "lopezmoussa@gmail.com",
        idRol: 6,
        legajo: "20698432",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351345452",
        direccion: "2553 Creola Springs",
        fechanacimiento: "29/05/1980"
    },
    {
        id: 100,
        login: "fabiola ",
        password: "123456",
        nombre: "Fabiola ",
        apellido: "Miralles",
        correo: "mirallesfabiola@gmail.com",
        idRol: 6,
        legajo: "20493532",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351612452",
        direccion: "1432 Hudson Point",
        fechanacimiento: "18/02/1970"
    },
    {
        id: 101,
        login: "melanie",
        password: "123456",
        nombre: "Melanie",
        apellido: "Espin",
        correo: "espinmelanie@gmail.com",
        idRol: 6,
        legajo: "20458324",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351454752",
        direccion: "533 Gleason Wall",
        fechanacimiento: "11/01/1973"
    },
    {
        id: 102,
        login: "carlota ",
        password: "123456",
        nombre: "Carlota ",
        apellido: "Padilla",
        correo: "padillacarlota@gmail.com",
        idRol: 6,
        legajo: "20463632",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351634542",
        direccion: "3718 Haag Forks",
        fechanacimiento: "20/09/1969"
    },
    {
        id: 103,
        login: "pepe",
        password: "123456",
        nombre: "Pepe",
        apellido: "Varela",
        correo: "varelapepe@gmail.com",
        idRol: 6,
        legajo: "23405543",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351345452",
        direccion: "1081 Jones Forge",
        fechanacimiento: "27/08/1971"
    },
    {
        id: 104,
        login: "gines",
        password: "123456",
        nombre: "Gines  ",
        apellido: "Boix",
        correo: "boixgines@gmail.com",
        idRol: 6,
        legajo: "20243932",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351345892",
        direccion: "073 Franecki Junction",
        fechanacimiento: "09/06/1979"
    },
    {
        id: 105,
        login: "leandro",
        password: "123456",
        nombre: "Leandro",
        apellido: "Alcalde",
        correo: "alcaldeleandro@gmail.com",
        idRol: 6,
        legajo: "20643734",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351342452",
        direccion: "79919 Amparo Route",
        fechanacimiento: "23/06/1969"
    },
    {
        id: 106,
        login: "henar",
        password: "123456",
        nombre: "Henar ",
        apellido: "Camino",
        correo: "caminohenar@gmail.com",
        idRol: 6,
        legajo: "20433272",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351334452",
        direccion: "13776 Angela Gardens",
        fechanacimiento: "25/06/1972"
    },
    {
        id: 107,
        login: "ibai",
        password: "123456",
        nombre: "Ibai",
        apellido: "Chaparro",
        correo: "chaparroibai@gmail.com",
        idRol: 6,
        legajo: "20684644",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351344572",
        direccion: "90585 Isabel Union",
        fechanacimiento: "03/03/1981"
    },
    {
        id: 108,
        login: "alexia",
        password: "123456",
        nombre: "Alexia ",
        apellido: "Luna",
        correo: "lunaalexia@gmail.com",
        idRol: 6,
        legajo: "20586343",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351634528",
        direccion: "1483 Stoltenberg Viaduct",
        fechanacimiento: "21/02/1972"
    },
    {
        id: 109,
        login: "irene ",
        password: "123456",
        nombre: "Irene",
        apellido: "Fraga",
        correo: "fragairene@gmail.com",
        idRol: 6,
        legajo: "23534953",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351343521",
        direccion: "91963 Kenyatta Underpass",
        fechanacimiento: "15/12/1976"
    },
    {
        id: 110,
        login: "juana ",
        password: "123456",
        nombre: "Juana",
        apellido: "Ferrer",
        correo: "ferrerjuana@gmail.com",
        idRol: 6,
        legajo: "21429434",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351634452",
        direccion: "59862 Bernhard Valleys",
        fechanacimiento: "24/07/1979"
    },
    {
        id: 111,
        login: "giovanni",
        password: "123456",
        nombre: "Giovanni",
        apellido: "Giraldo",
        correo: "giraldogiovanni@gmail.com",
        idRol: 6,
        legajo: "21374342",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351343528",
        direccion: "5704 Kuhn Avenue",
        fechanacimiento: "25/09/1979"
    },
    {
        id: 112,
        login: "jeronima",
        password: "123456",
        nombre: "Jeronima",
        apellido: "Lozano",
        correo: "lozanojeronima@gmail.com",
        idRol: 6,
        legajo: "20586342",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351322452",
        direccion: "6845 Wolf Village",
        fechanacimiento: "01/04/1971"
    },
    {
        id: 113,
        login: "nicolasa ",
        password: "123456",
        nombre: "Nicolasa ",
        apellido: "Cristobal",
        correo: "cristobalnicolasa@gmail.com",
        idRol: 6,
        legajo: "20564843",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351634452",
        direccion: "137 VonRueden Pine",
        fechanacimiento: "01/07/1971"
    },
    {
        id: 114,
        login: "flora ",
        password: "123456",
        nombre: "Flora ",
        apellido: "Sierra",
        correo: "sierraflora@gmail.com",
        idRol: 6,
        legajo: "21433734",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351645942",
        direccion: "52991 Camren Wells",
        fechanacimiento: "16/11/1977"
    },
    {
        id: 115,
        login: "alberto",
        password: "123456",
        nombre: "Alberto ",
        apellido: "Palazon",
        correo: "palazonalberto@gmail.com",
        idRol: 6,
        legajo: "23655964",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351343527",
        direccion: "42369 Cassin Tunnel",
        fechanacimiento: "25/06/1976"
    },
    {
        id: 116,
        login: "julian ",
        password: "123456",
        nombre: "Julian ",
        apellido: "Jurado",
        correo: "juradojulian@gmail.com",
        idRol: 6,
        legajo: "20538734",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351634452",
        direccion: "219 Becker Stravenue",
        fechanacimiento: "23/03/1973"
    },
    {
        id: 117,
        login: "gabriela",
        password: "123456",
        nombre: "Gabriela ",
        apellido: "Navarrete",
        correo: "navarretegabriela@gmail.com",
        idRol: 6,
        legajo: "21559833",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351343452",
        direccion: "058 Rolfson Cove",
        fechanacimiento: "12/04/1982"
    },
    {
        id: 118,
        login: "rut",
        password: "123456",
        nombre: "Rut",
        apellido: "San Jose",
        correo: "sanjoserurutben@gmail.com",
        idRol: 6,
        legajo: "20856534",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351344527",
        direccion: "71289 Steuber Hill",
        fechanacimiento: "28/05/1980"
    },
    {
        id: 119,
        login: "amparo",
        password: "123456",
        nombre: "Amparo",
        apellido: "Mendoza",
        correo: "mendozaamparo@gmail.com",
        idRol: 6,
        legajo: "20437343",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351343321",
        direccion: "376 Wyman Cliff",
        fechanacimiento: "21/08/1981"
    },
    {
        id: 120,
        login: "nayra",
        password: "123456",
        nombre: "Nayra ",
        apellido: "Losada",
        correo: "losadanayra@gmail.com",
        idRol: 6,
        legajo: "23453474",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "351623528",
        direccion: "04517 Aufderhar Circle",
        fechanacimiento: "07/05/1969"
    },
    {
        id: 121,
        login: "iker",
        password: "123456",
        nombre: "Iker ",
        apellido: "Font",
        correo: "fontiker@gmail.com",
        idRol: 6,
        legajo: "24373532",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351434521",
        direccion: "72891 Bednar Tunnel",
        fechanacimiento: "06/07/1981"
    }
]

