export const usuarios = [
    {
        login: "admin",
        password: "123456",
        nombre: "Admin",
        apellido: "Sistema",
        correo: "admin@gmail.com",
        rol: {
            id: 4,
            tipo: 'Administrador'
        },
        legajo: "3423431",
        sexo: "M",
        localidad: "Buenos Aires",
        telefono: "351612452",
        direccion: "Caseros 343",

    },
    {
        login: "bruno",
        password: "123456",
        nombre: "Bruno",
        apellido: "Carnero",
        correo: "carnero@gmail.com",
        rol: {
            id: 1,
            tipo: 'Estudiante'
        },
        legajo: "555463",
        sexo: "M",
        localidad: "Buenos Aires",
        telefono: "56452445",
        direccion: "Caseros 563",

    },
    {
        login: "luis",
        password: "123456",
        nombre: "Luis",
        apellido: "Aguilar",
        correo: "aguilar@gmail.com",
        rol: {
            id: 2,
            tipo: 'Director'
        },
        legajo: "564352",
        sexo: "M",
        localidad: "Buenos Aires",
        telefono: "351545642",
        direccion: "Caseros 234",

    },
    {
        login: "samuel",
        password: "123456",
        nombre: "Samuel",
        apellido: "Paredez",
        correo: "paredez@gmail.com",
        rol: {
            id: 3,
            tipo: 'Docente'
        },
        legajo: "242333",
        sexo: "M",
        localidad: "Buenos Aires",
        telefono: "351678452",
        direccion: "Casas 434",

    },
    {
        login: "lucia",
        password: "123456",
        nombre: "Lucia",
        apellido: "Rodriguez",
        correo: "rodriguez@gmail.com",
        rol: {
            id: 5,
            tipo: 'Vicedirector'
        },
        legajo: "3353233",
        sexo: "M",
        localidad: "Buenos Aires",
        telefono: "351467532",
        direccion: "Siempre Viva 343",
    },
    {
        login: "jacinto",
        password: "123456",
        nombre: "Jacinto",
        apellido: "Del Valle",
        correo: "delvalle@gmail.com",
        rol: {
            id: 6,
            tipo: 'Preceptor'
        },
        legajo: "3423431",
        sexo: "M",
        localidad: "Buenos Aires",
        telefono: "35161755752",
        direccion: "Caseros 343",

    },
    {
        login: "hector",
        password: "123456",
        nombre: "Hector",
        apellido: "Urbano",
        correo: "hector@gmail.com",
        rol: {
            id: 3,
            tipo: 'Docente'
        },
        legajo: "2325312",
        sexo: "M",
        localidad: "Buenos Aires",
        telefono: "351615252",
        direccion: "Caseros 323"
    },
    {
        login: "Leonardo",
        password: "123456",
        nombre: "Leonardo",
        apellido: "Trigo",
        correo: "leonardo@gmail.com",
        rol: {
            id: 3,
            tipo: 'Docente'
        },
        legajo: "435212",
        sexo: "M",
        localidad: "Buenos Aires",
        telefono: "351645452",
        direccion: "Caseros 423"
    },
    {
        login: "Mireia",
        password: "123456",
        nombre: "Mireia",
        apellido: "Lucena",
        correo: "lucena@gmail.com",
        rol: {
            id: 3,
            tipo: 'Docente'
        },
        legajo: "3431242",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "3516144352",
        direccion: "9922 Domenica Passage"
    },
    {
        login: "Reyes ",
        password: "123456",
        nombre: "Reyes ",
        apellido: "Gomis",
        correo: "gomis@gmail.com",
        rol: {
            id: 3,
            tipo: 'Docente'
        },
        legajo: "3345312",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "3516125452",
        direccion: "6844 Abshire Plaza"
    },
    {
        login: "Mariano",
        password: "123456",
        nombre: "Mariano",
        apellido: "Morillas",
        correo: "morillas@gmail.com",
        rol: {
            id: 3,
            tipo: 'Docente'
        },
        legajo: "434122",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "3516154352",
        direccion: "1352 Alberta Loaf"
    },
    {
        login: "iban",
        password: "123456",
        nombre: "Iban ",
        apellido: "Puerta",
        correo: "@gmail.com",
        rol: {
            id: 1,
            tipo: 'Estudiante'
        },
        legajo: "344312",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "3513412452",
        direccion: "12900 White Spur"
    },
    {
        login: "patricia",
        password: "123456",
        nombre: "Patricia ",
        apellido: "Penalver",
        correo: "patricia@gmail.com",
        rol: {
            id: 1,
            tipo: 'Estudiante'
        },
        legajo: "454332",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "3516124352",
        direccion: "20424 Maximillian Hollow"
    },
    {
        login: "noel ",
        password: "123456",
        nombre: "Noel ",
        apellido: "Crespo",
        correo: "crespo@gmail.com",
        rol: {
            id: 1,
            tipo: 'Estudiante'
        },
        legajo: "3431253",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351342452",
        direccion: "035 Roberto Forges"
    },
    {
        login: "serafin ",
        password: "123456",
        nombre: "Serafin ",
        apellido: "Galindo",
        correo: "galindo@gmail.com",
        rol: {
            id: 1,
            tipo: 'Estudiante'
        },
        legajo: "3434212",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "351612452",
        direccion: "124 Pollich Corner"
    },
    {
        login: "leonor ",
        password: "123456",
        nombre: "Leonor ",
        apellido: "del Moral",
        correo: "leonor@gmail.com",
        rol: {
            id: 1,
            tipo: 'Estudiante'
        },
        legajo: "433433",
        sexo: "F",
        localidad: "Cordoba",
        telefono: "3516125442",
        direccion: "966 Evalyn Manor"
    },
    {
        login: "antonio",
        password: "123456",
        nombre: "Antonio ",
        apellido: "Bustamante",
        correo: "antonio@gmail.com",
        rol: {
            id: 1,
            tipo: 'Estudiante'
        },
        legajo: "34344",
        sexo: "M",
        localidad: "Cordoba",
        telefono: "3513232452",
        direccion: "68313 Dawson Meadow"
    },
    // {
    //     login: "virgilio",
    //     password: "123456",
    //     nombre: "Virgilio ",
    //     apellido: "Cano",
    //     correo: "virgilio@gmail.com",
    //     idRol: 6,
    //     legajo: "3544232",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351613432",
    //     direccion: "4002 Schiller Creek"
    // },
    // {
    //     login: "nicolae",
    //     password: "123456",
    //     nombre: "Nicolae ",
    //     apellido: "Garzon",
    //     correo: "nicolae@gmail.com",
    //     idRol: 6,
    //     legajo: "35323654",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351613252",
    //     direccion: "4042 Schiller Creek"
    // },
    // {
    //     login: "andres",
    //     password: "123456",
    //     nombre: "Andres",
    //     apellido: "Acuña",
    //     correo: "andres@gmail.com",
    //     idRol: 6,
    //     legajo: "54643432",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351634223",
    //     direccion: "4508 Madelyn Ways"
    // },
    // {
    //     login: "virgilio",
    //     password: "123456",
    //     nombre: "Virgilio ",
    //     apellido: "Puente",
    //     correo: "virgilio@gmail.com",
    //     idRol: 6,
    //     legajo: "4434324",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "3516565452",
    //     direccion: "9414 Koepp Loop"
    // },
    // {
    //     login: "florencio",
    //     password: "123456",
    //     nombre: "Florencio ",
    //     apellido: "Aranda",
    //     correo: "florencio@gmail.com",
    //     idRol: 6,
    //     legajo: "57564343",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351545452",
    //     direccion: "80586 Petra Haven"
    // },
    // {
    //     login: "yurena",
    //     password: "123456",
    //     nombre: "Yurena ",
    //     apellido: "Gamero",
    //     correo: "yurena@gmail.com",
    //     idRol: 6,
    //     legajo: "4543432",
    //     sexo: "F",
    //     localidad: "Cordoba",
    //     telefono: "351675652",
    //     direccion: "19289 Spencer Valleys"
    // },
    // {
    //     login: "nil",
    //     password: "123456",
    //     nombre: "Nil",
    //     apellido: "Hernando",
    //     correo: "nil@gmail.com",
    //     idRol: 6,
    //     legajo: "7564434",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "19765 Spencer Valleys"
    // },
    // {
    //     login: "martos",
    //     password: "123456",
    //     nombre: "Luciana",
    //     apellido: "Martos",
    //     correo: "martos@gmail.com",
    //     idRol: 6,
    //     legajo: "768546",
    //     sexo: "F",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "0032 Krajcik Path"
    // },
    // {
    //     login: "luis",
    //     password: "123456",
    //     nombre: "Luis",
    //     apellido: "Moya",
    //     correo: "luis@gmail.com",
    //     idRol: 6,
    //     legajo: "876568",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "3655 Jairo Mall"
    // },
    // {
    //     login: "eloisa",
    //     password: "123456",
    //     nombre: "Eloisa",
    //     apellido: "Diego",
    //     correo: "eloisa@gmail.com",
    //     idRol: 6,
    //     legajo: "456667",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "0728 Raymundo Plains"
    // },
    // {
    //     login: "fran",
    //     password: "123456",
    //     nombre: "Fran",
    //     apellido: "Cerda",
    //     correo: "fran@gmail.com",
    //     idRol: 6,
    //     legajo: "543888",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "1760 Renner Loop"
    // },
    // {
    //     login: "mohammed",
    //     password: "123456",
    //     nombre: "Mohammed",
    //     apellido: "Nogales",
    //     correo: "mohammed@gmail.com",
    //     idRol: 6,
    //     legajo: "656695",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "6199 Mara Street"
    // },
    // {
    //     login: "malak",
    //     password: "123456",
    //     nombre: "Malak",
    //     apellido: "Rueda",
    //     correo: "malak@gmail.com",
    //     idRol: 6,
    //     legajo: "4355876",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "4874 Bauch Junctions"
    // },
    // {
    //     login: "gisela",
    //     password: "123456",
    //     nombre: "Gisela",
    //     apellido: "Santana",
    //     correo: "gisela@gmail.com",
    //     idRol: 6,
    //     legajo: "464532",
    //     sexo: "F",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "98849 Reilly Ports"
    // },
    // {
    //     login: "isaias",
    //     password: "123456",
    //     nombre: "Isaias ",
    //     apellido: "Quiros",
    //     correo: "isaias@gmail.com",
    //     idRol: 6,
    //     legajo: "",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "2750 Trantow Stream"
    // },
    // {
    //     login: "minerva",
    //     password: "123456",
    //     nombre: "Minerva ",
    //     apellido: "Mata",
    //     correo: "minerva@gmail.com",
    //     idRol: 6,
    //     legajo: "5434322",
    //     sexo: "F",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "4283 Schamberger Crossroad"
    // },
    // {
    //     login: "mercedes ",
    //     password: "123456",
    //     nombre: "Mercedes ",
    //     apellido: "Canovas",
    //     correo: "mercedes@gmail.com",
    //     idRol: 6,
    //     legajo: "567543",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "5544 Weissnat Rest"
    // },
    // {
    //     login: "sara",
    //     password: "123456",
    //     nombre: "Sara",
    //     apellido: "Peinado",
    //     correo: "sara@gmail.com",
    //     idRol: 6,
    //     legajo: "4522323",
    //     sexo: "F",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "369 Nathen Well"
    // },
    // {
    //     login: "said",
    //     password: "123456",
    //     nombre: "Said ",
    //     apellido: "Cid",
    //     correo: "said@gmail.com",
    //     idRol: 6,
    //     legajo: "4543453",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "251 Reinger Road"
    // },
    // {
    //     login: "oriol",
    //     password: "123456",
    //     nombre: "Oriol",
    //     apellido: "Bermudez",
    //     correo: "oriol@gmail.com",
    //     idRol: 6,
    //     legajo: "421323",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "3781 Gene Mission"
    // },
    // {
    //     login: "carolina",
    //     password: "123456",
    //     nombre: "Carolina ",
    //     apellido: "Lopez",
    //     correo: "carolina@gmail.com",
    //     idRol: 6,
    //     legajo: "456432",
    //     sexo: "F",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "2553 Creola Springs"
    // },
    // {
    //     login: "mihaela",
    //     password: "123456",
    //     nombre: "Mihaela ",
    //     apellido: "Miralles",
    //     correo: "mihaela@gmail.com",
    //     idRol: 6,
    //     legajo: "4243532",
    //     sexo: "F",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "1432 Hudson Point"
    // },
    // {
    //     login: "angel",
    //     password: "123456",
    //     nombre: "Angel ",
    //     apellido: "Espin",
    //     correo: "angel@gmail.com",
    //     idRol: 6,
    //     legajo: "4345324",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "533 Gleason Wall"
    // },
    // {
    //     login: "antoni",
    //     password: "123456",
    //     nombre: "Antoni",
    //     apellido: "Padilla",
    //     correo: "antoni@gmail.com",
    //     idRol: 6,
    //     legajo: "4346332",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "3718 Haag Forks"
    // },
    // {
    //     login: "maribel",
    //     password: "123456",
    //     nombre: "Maribel",
    //     apellido: "Varela",
    //     correo: "maribel@gmail.com",
    //     idRol: 6,
    //     legajo: "434553",
    //     sexo: "F",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "1081 Jones Forge"
    // },
    // {
    //     login: "hafida",
    //     password: "123456",
    //     nombre: "Hafida ",
    //     apellido: "Boix",
    //     correo: "hafida@gmail.com",
    //     idRol: 6,
    //     legajo: "4524332",
    //     sexo: "F",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "073 Franecki Junction"
    // },
    // {
    //     login: "merce",
    //     password: "123456",
    //     nombre: "Merce",
    //     apellido: "Alcalde",
    //     correo: "merce@gmail.com",
    //     idRol: 6,
    //     legajo: "434564334",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "79919 Amparo Route"
    // },
    // {
    //     login: "aranzazu",
    //     password: "123456",
    //     nombre: "Aranzazu",
    //     apellido: "Camino",
    //     correo: "aranzazu@gmail.com",
    //     idRol: 6,
    //     legajo: "5343322",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "13776 Angela Gardens"
    // },
    // {
    //     login: "najat",
    //     password: "123456",
    //     nombre: "Najat",
    //     apellido: "Chaparro",
    //     correo: "najat@gmail.com",
    //     idRol: 6,
    //     legajo: "43464644",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "90585 Isabel Union"
    // },
    // {
    //     login: "marwa",
    //     password: "123456",
    //     nombre: "Marwa",
    //     apellido: "Luna",
    //     correo: "marwa@gmail.com",
    //     idRol: 6,
    //     legajo: "4356343",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "1483 Stoltenberg Viaduct"
    // },
    // {
    //     login: "mayte",
    //     password: "123456",
    //     nombre: "Mayte ",
    //     apellido: "Fraga",
    //     correo: "mayte@gmail.com",
    //     idRol: 6,
    //     legajo: "4453453",
    //     sexo: "F",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "91963 Kenyatta Underpass"
    // },
    // {
    //     login: "dominga",
    //     password: "123456",
    //     nombre: "Dominga ",
    //     apellido: "Ferrer",
    //     correo: "dominga@gmail.com",
    //     idRol: 6,
    //     legajo: "4242434",
    //     sexo: "F",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "59862 Bernhard Valleys"
    // },
    // {
    //     login: "gerardo",
    //     password: "123456",
    //     nombre: "Gerardo",
    //     apellido: "Giraldo",
    //     correo: "gerardo@gmail.com",
    //     idRol: 6,
    //     legajo: "4434342",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "5704 Kuhn Avenue"
    // },
    // {
    //     login: "vega",
    //     password: "123456",
    //     nombre: "Vega",
    //     apellido: "Lozano",
    //     correo: "vega@gmail.com",
    //     idRol: 6,
    //     legajo: "445342",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "6845 Wolf Village"
    // },
    // {
    //     login: "bilal",
    //     password: "123456",
    //     nombre: "Bilal",
    //     apellido: "Cristobal",
    //     correo: "bilal@gmail.com",
    //     idRol: 6,
    //     legajo: "4356443",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "137 VonRueden Pine"
    // },
    // {
    //     login: "lydia",
    //     password: "123456",
    //     nombre: "Lydia",
    //     apellido: "Sierra",
    //     correo: "lydia@gmail.com",
    //     idRol: 6,
    //     legajo: "4343334",
    //     sexo: "F",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "52991 Camren Wells"
    // },
    // {
    //     login: "pilar",
    //     password: "123456",
    //     nombre: "Pilar",
    //     apellido: "Palazon",
    //     correo: "pilar@gmail.com",
    //     idRol: 6,
    //     legajo: "43565564",
    //     sexo: "F",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "42369 Cassin Tunnel"
    // },
    // {
    //     login: "ainara",
    //     password: "123456",
    //     nombre: "Ainara",
    //     apellido: "Jurado",
    //     correo: "ainara@gmail.com",
    //     idRol: 6,
    //     legajo: "435334",
    //     sexo: "F",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "219 Becker Stravenue"
    // },
    // {
    //     login: "lucia",
    //     password: "123456",
    //     nombre: "Lucia",
    //     apellido: "Navarrete",
    //     correo: "lucia@gmail.com",
    //     idRol: 6,
    //     legajo: "435533",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "058 Rolfson Cove"
    // },
    // {
    //     login: "ruben",
    //     password: "123456",
    //     nombre: "Ruben",
    //     apellido: "San Jose",
    //     correo: "ruben@gmail.com",
    //     idRol: 6,
    //     legajo: "43534",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "71289 Steuber Hill"
    // },
    // {
    //     login: "andoni",
    //     password: "123456",
    //     nombre: "Andoni",
    //     apellido: "Mendoza",
    //     correo: "andoni@gmail.com",
    //     idRol: 6,
    //     legajo: "5343343",
    //     sexo: "M",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "376 Wyman Cliff"
    // },
    // {
    //     login: "basilisa",
    //     password: "123456",
    //     nombre: "Basilisa",
    //     apellido: "Losada",
    //     correo: "basilisa@gmail.com",
    //     idRol: 6,
    //     legajo: "4345344",
    //     sexo: "F",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "04517 Aufderhar Circle"
    // },
    // {
    //     login: "rebeca",
    //     password: "123456",
    //     nombre: "Rebeca",
    //     apellido: "Font",
    //     correo: "rebeca@gmail.com",
    //     idRol: 6,
    //     legajo: "5433532",
    //     sexo: "F",
    //     localidad: "Cordoba",
    //     telefono: "351612452",
    //     direccion: "72891 Bednar Tunnel"
    // },
]

