import Head from "next/head";
import styles from '../styles/loginLayout.module.css'

export default function LoginLayout({ children }) {
    return (
        <>
            <Head>
                <title>Iniciar Sesion</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo_instituto.png" />
                <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css" />
            </Head>
            <div className={`${styles.container} ${styles.login_container}`}>
                <div className="row">
                    <div className={`col-md-6 ${styles.login_form_1}`}>

                    </div>
                    <div className={`col-md-6 ${styles.login_form_2}`}>
                        {children}
                    </div>
                </div>
            </div>
            <script defer src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
            <script defer src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        </>
    )
}