import Head from "next/head";
import Image from "next/image";
import { Col, Container, Row } from "reactstrap";

export default function LoginLayout({ children }) {
    return (
        <>
            <Head>
                <title>Login or Register</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container style={{ marginTop: '5%', marginBottom: '5%' }}>
                <Row>
                    <Col md={6} style={
                        {
                            padding: '9%',
                            background: "url('/assets/img/portada.jpg')",
                            boxShadow: '0 5px 8px 0 rgba(0, 0, 0, 0.2), 0 9px 26px 0 rgba(0, 0, 0, 0.19)'
                        }
                    }>
                    </Col>
                    <Col md={6} style={
                        {
                            padding: '9%',
                            boxShadow: '0 5px 8px 0 rgba(0, 0, 0, 0.2), 0 9px 26px 0 rgba(0, 0, 0, 0.19)'
                        }
                    }>
                        {children}
                    </Col>
                </Row>
            </Container>
        </>
    )
}